//! Cognitive-provenance-graph types.
//!
//! These types track the **origin** of AI-generated artifacts. Every code block,
//! file change, or significant output is linked back to the prompt, tool call,
//! or thought that produced it — enabling audit, debugging, replay, and *blame*
//! for AI agents.

use serde::{Deserialize, Serialize};

use super::common::{Confidence, Range};

/// How an artifact was produced.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ProvenanceSource {
    /// Direct output of a language model.
    ModelOutput,
    /// Result of executing a tool.
    ToolExecution,
    /// Result of running a test.
    TestRun,
    /// User-supplied input.
    UserInput,
    /// Generated by an agent's reasoning.
    Reasoning,
    /// Extracted from existing code.
    CodeExtraction,
    /// Loaded from a file on disk.
    FileLoad,
    /// Composed from other artifacts.
    Composition,
    /// Inferred / deduced (no direct source).
    Inference,
}

impl ProvenanceSource {
    /// Stable identifier.
    #[must_use]
    pub const fn id(self) -> &'static str {
        match self {
            Self::ModelOutput => "model_output",
            Self::ToolExecution => "tool_execution",
            Self::TestRun => "test_run",
            Self::UserInput => "user_input",
            Self::Reasoning => "reasoning",
            Self::CodeExtraction => "code_extraction",
            Self::FileLoad => "file_load",
            Self::Composition => "composition",
            Self::Inference => "inference",
        }
    }
}

/// A single provenance record describing one artifact.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ProvenanceRecord {
    /// Stable identifier.
    pub id: String,
    /// The artifact this record describes (e.g. file path, function name, …).
    pub artifact: String,
    /// Source of the artifact.
    pub source: ProvenanceSource,
    /// Specific tool / model / function that produced it.
    pub origin: String,
    /// Optional parent record (for chained generation).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parent: Option<String>,
    /// Children record IDs (for chained generation).
    #[serde(default)]
    pub children: Vec<String>,
    /// Original prompt or instruction (truncated for large prompts).
    pub prompt: String,
    /// Raw content of the artifact.
    pub content: String,
    /// Hash of the content for fast equality.
    pub content_hash: String,
    /// When the artifact was produced (Unix seconds).
    pub timestamp: i64,
    /// Agent / session that produced it.
    pub agent: String,
    /// Optional location in a file.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub location: Option<Range>,
    /// Confidence in `[0.0, 1.0]`.
    pub confidence: Confidence,
    /// Free-form metadata.
    #[serde(default)]
    pub metadata: indexmap::IndexMap<String, String>,
}

impl ProvenanceRecord {
    /// Construct a new provenance record.
    #[must_use]
    pub fn new(
        artifact: impl Into<String>,
        source: ProvenanceSource,
        origin: impl Into<String>,
        prompt: impl Into<String>,
        content: impl Into<String>,
        agent: impl Into<String>,
    ) -> Self {
        use sha2::{Digest, Sha256};
        let content_string: String = content.into();
        let mut hasher = Sha256::new();
        hasher.update(content_string.as_bytes());
        let content_hash = format!("{:x}", hasher.finalize());

        Self {
            id: uuid::Uuid::new_v4().to_string(),
            artifact: artifact.into(),
            source,
            origin: origin.into(),
            parent: None,
            children: Vec::new(),
            prompt: prompt.into(),
            content: content_string,
            content_hash,
            timestamp: chrono::Utc::now().timestamp(),
            agent: agent.into(),
            location: None,
            confidence: Confidence::default(),
            metadata: indexmap::IndexMap::new(),
        }
    }

    /// Compute the SHA-256 hash of the given content.
    #[must_use]
    pub fn hash_of(content: &str) -> String {
        use sha2::{Digest, Sha256};
        let mut hasher = Sha256::new();
        hasher.update(content.as_bytes());
        format!("{:x}", hasher.finalize())
    }
}

/// Type of edge in the provenance graph.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ProvenanceEdgeType {
    /// B was directly produced by A.
    ProducedBy,
    /// B was derived from A.
    DerivedFrom,
    /// B refactored A.
    RefactoredFrom,
    /// B tested A.
    TestsAgainst,
    /// B is a sibling of A (same prompt, different artifacts).
    Sibling,
    /// B documents A.
    Documents,
}

impl ProvenanceEdgeType {
    /// Stable identifier.
    #[must_use]
    pub const fn id(self) -> &'static str {
        match self {
            Self::ProducedBy => "produced_by",
            Self::DerivedFrom => "derived_from",
            Self::RefactoredFrom => "refactored_from",
            Self::TestsAgainst => "tests_against",
            Self::Sibling => "sibling",
            Self::Documents => "documents",
        }
    }
}

/// An edge in the provenance graph.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ProvenanceEdge {
    /// Source record ID.
    pub from: String,
    /// Target record ID.
    pub to: String,
    /// Edge type.
    pub edge_type: ProvenanceEdgeType,
    /// Optional notes.
    #[serde(default)]
    pub notes: String,
}

/// The full Cognitive Provenance Graph.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ProvenanceGraph {
    /// All records.
    pub records: Vec<ProvenanceRecord>,
    /// All edges.
    pub edges: Vec<ProvenanceEdge>,
    /// Stable identifier for the graph itself.
    pub id: String,
    /// Timestamp.
    pub timestamp: chrono::DateTime<chrono::Utc>,
    /// Optional project / session name.
    #[serde(default)]
    pub name: String,
}

impl ProvenanceGraph {
    /// Find a record by ID.
    #[must_use]
    pub fn record(&self, id: &str) -> Option<&ProvenanceRecord> {
        self.records.iter().find(|r| r.id == id)
    }

    /// Find records for a specific artifact.
    #[must_use]
    pub fn records_for_artifact(&self, artifact: &str) -> Vec<&ProvenanceRecord> {
        self.records
            .iter()
            .filter(|r| r.artifact == artifact)
            .collect()
    }

    /// Find records produced by a specific agent.
    #[must_use]
    pub fn records_by_agent(&self, agent: &str) -> Vec<&ProvenanceRecord> {
        self.records.iter().filter(|r| r.agent == agent).collect()
    }

    /// Records produced directly from a specific source type.
    #[must_use]
    pub fn records_with_source(&self, source: ProvenanceSource) -> Vec<&ProvenanceRecord> {
        self.records.iter().filter(|r| r.source == source).collect()
    }

    /// Outgoing edges from a record.
    pub fn outgoing(&self, id: &str) -> impl Iterator<Item = &ProvenanceEdge> {
        self.edges.iter().filter(move |e| e.from == id)
    }

    /// Incoming edges to a record.
    pub fn incoming(&self, id: &str) -> impl Iterator<Item = &ProvenanceEdge> {
        self.edges.iter().filter(move |e| e.to == id)
    }

    /// Walk the chain of ancestry for a record.
    #[must_use]
    pub fn ancestors_of(&self, id: &str) -> Vec<&ProvenanceRecord> {
        let mut ancestors = Vec::new();
        let mut current = self.record(id).and_then(|r| r.parent.clone());
        let mut seen = std::collections::HashSet::new();
        while let Some(parent_id) = current {
            if !seen.insert(parent_id.clone()) {
                break;
            }
            if let Some(parent) = self.record(&parent_id) {
                ancestors.push(parent);
                current = parent.parent.clone();
            } else {
                break;
            }
        }
        ancestors
    }
}

/// A query result against the provenance graph.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ProvenanceQuery {
    /// Free-form description of the query.
    pub description: String,
    /// Matching records.
    pub records: Vec<ProvenanceRecord>,
    /// Number of records scanned.
    pub scanned: usize,
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_record(artifact: &str) -> ProvenanceRecord {
        ProvenanceRecord::new(
            artifact,
            ProvenanceSource::ModelOutput,
            "claude-opus-4",
            "fix the bug",
            "fn x() {}",
            "agent-1",
        )
    }

    #[test]
    fn hash_is_deterministic() {
        let h1 = ProvenanceRecord::hash_of("hello");
        let h2 = ProvenanceRecord::hash_of("hello");
        assert_eq!(h1, h2);
        let h3 = ProvenanceRecord::hash_of("world");
        assert_ne!(h1, h3);
    }

    #[test]
    fn source_ids_are_stable() {
        assert_eq!(ProvenanceSource::ModelOutput.id(), "model_output");
        assert_eq!(ProvenanceSource::ToolExecution.id(), "tool_execution");
    }

    #[test]
    fn records_for_artifact_filters_correctly() {
        let g = ProvenanceGraph {
            records: vec![sample_record("a"), sample_record("b"), sample_record("a")],
            edges: vec![],
            id: "g".into(),
            timestamp: chrono::Utc::now(),
            name: String::new(),
        };
        assert_eq!(g.records_for_artifact("a").len(), 2);
    }
}
